/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package capa_presentacion;

import capa_datos.Voto;
import capa_logica.VotacionServicio.ResultadosTotales;
import java.util.Arrays;
import java.util.List;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;

/**
 *
 * @author NAYR VASQUEZ
 */
public class frmVotacion extends javax.swing.JFrame {
  
    private capa_logica.VotacionServicio service;
    
    private Map<String, List<String>> data = new HashMap<>();

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frmVotacion.class.getName());

    /**
     * Creates new form frmVotacion
     */
    public frmVotacion(java.awt.Frame parent, boolean modal) {
        initComponents();
        service = new capa_logica.VotacionServicio();
        initData();
        actualizarSelectores();
        actualizarResultados();
    }

    private void initData() {

        data.put("PERÚ", Arrays.asList(
            "AMAZONAS", "ÁNCASH", "APURÍMAC", "AREQUIPA", "AYACUCHO",
            "CAJAMARCA", "CALLAO", "CUSCO", "HUANCAVELICA", "HUÁNUCO",
            "ICA", "JUNÍN", "LA LIBERTAD", "LAMBAYEQUE", "LIMA",
            "LORETO", "MADRE DE DIOS", "MOQUEGUA", "PASCO", "PIURA",
            "PUNO", "SAN MARTÍN", "TACNA", "TUMBES", "UCAYALI"
        ));


        data.put("EXTRANJERO", Arrays.asList(
            "ÁFRICA", "AMÉRICA", "ASIA", "EUROPA", "OCEANIA"
        ));

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        JPanelKeiko = new javax.swing.JPanel();
        lblFotoKeiko = new javax.swing.JLabel();
        lblPorcentajeKeiko = new javax.swing.JLabel();
        lblNombresKeiko = new javax.swing.JLabel();
        lblVotosKeiko = new javax.swing.JLabel();
        lblFuerzaPopular = new javax.swing.JLabel();
        lblApellidosKeiko1 = new javax.swing.JLabel();
        JPanelKeiko1 = new javax.swing.JPanel();
        lblFotoSanchez = new javax.swing.JLabel();
        lblPorcentajeSanchez = new javax.swing.JLabel();
        lblNombresSanchez = new javax.swing.JLabel();
        lblApellidosSanchez = new javax.swing.JLabel();
        lblFuerzaPopular1 = new javax.swing.JLabel();
        lblVotosSanchez = new javax.swing.JLabel();
        cboAmbito = new javax.swing.JComboBox<>();
        cboRegion = new javax.swing.JComboBox<>();
        lblAmbito = new javax.swing.JLabel();
        lblRegion = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtVotosKeiko = new javax.swing.JTextField();
        txtVotosSanchez = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();
        btnReporte_G1 = new javax.swing.JButton();
        btnReporte_G2 = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(0, 51, 102));
        lblTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Captura de pantalla 2026-06-22 171242.png"))); // NOI18N
        lblTitulo.setText("Elección de Fórmula Presidencial");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        JPanelKeiko.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblFotoKeiko.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/KeikoFujimori.jpeg"))); // NOI18N

        lblPorcentajeKeiko.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblPorcentajeKeiko.setForeground(new java.awt.Color(0, 51, 102));
        lblPorcentajeKeiko.setText("0.00%");

        lblNombresKeiko.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblNombresKeiko.setForeground(new java.awt.Color(0, 51, 102));
        lblNombresKeiko.setText("KEIKO SOFIA");

        lblVotosKeiko.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblVotosKeiko.setForeground(new java.awt.Color(0, 51, 102));
        lblVotosKeiko.setText("0 votos");

        lblFuerzaPopular.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblFuerzaPopular.setForeground(new java.awt.Color(153, 153, 153));
        lblFuerzaPopular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/logoFuerzaPopular.jpeg"))); // NOI18N
        lblFuerzaPopular.setText("FUERZA POPULAR");

        lblApellidosKeiko1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblApellidosKeiko1.setForeground(new java.awt.Color(0, 51, 102));
        lblApellidosKeiko1.setText("FUJIMORI HIGUCHI");

        javax.swing.GroupLayout JPanelKeikoLayout = new javax.swing.GroupLayout(JPanelKeiko);
        JPanelKeiko.setLayout(JPanelKeikoLayout);
        JPanelKeikoLayout.setHorizontalGroup(
            JPanelKeikoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelKeikoLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lblFotoKeiko)
                .addGap(18, 18, 18)
                .addGroup(JPanelKeikoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNombresKeiko)
                    .addComponent(lblPorcentajeKeiko)
                    .addComponent(lblVotosKeiko)
                    .addComponent(lblFuerzaPopular)
                    .addComponent(lblApellidosKeiko1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JPanelKeikoLayout.setVerticalGroup(
            JPanelKeikoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelKeikoLayout.createSequentialGroup()
                .addGroup(JPanelKeikoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPanelKeikoLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(lblFotoKeiko))
                    .addGroup(JPanelKeikoLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(lblPorcentajeKeiko)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblNombresKeiko)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblApellidosKeiko1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblFuerzaPopular, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblVotosKeiko)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        JPanelKeiko1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblFotoSanchez.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/RobertoSanchez.jpeg"))); // NOI18N

        lblPorcentajeSanchez.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblPorcentajeSanchez.setForeground(new java.awt.Color(0, 51, 102));
        lblPorcentajeSanchez.setText("0.00%");

        lblNombresSanchez.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblNombresSanchez.setForeground(new java.awt.Color(0, 51, 102));
        lblNombresSanchez.setText("ROBERTO HELBERT");

        lblApellidosSanchez.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblApellidosSanchez.setForeground(new java.awt.Color(0, 51, 102));
        lblApellidosSanchez.setText("SANCHEZ PALOMINO");

        lblFuerzaPopular1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblFuerzaPopular1.setForeground(new java.awt.Color(153, 153, 153));
        lblFuerzaPopular1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/logoJP.jpeg"))); // NOI18N
        lblFuerzaPopular1.setText("JUNTOS POR EL PERÚ");

        lblVotosSanchez.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblVotosSanchez.setForeground(new java.awt.Color(0, 51, 102));
        lblVotosSanchez.setText("0 votos");

        javax.swing.GroupLayout JPanelKeiko1Layout = new javax.swing.GroupLayout(JPanelKeiko1);
        JPanelKeiko1.setLayout(JPanelKeiko1Layout);
        JPanelKeiko1Layout.setHorizontalGroup(
            JPanelKeiko1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelKeiko1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblFotoSanchez)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JPanelKeiko1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblVotosSanchez)
                    .addComponent(lblPorcentajeSanchez)
                    .addComponent(lblNombresSanchez)
                    .addComponent(lblApellidosSanchez)
                    .addComponent(lblFuerzaPopular1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JPanelKeiko1Layout.setVerticalGroup(
            JPanelKeiko1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelKeiko1Layout.createSequentialGroup()
                .addGroup(JPanelKeiko1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPanelKeiko1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lblPorcentajeSanchez)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblNombresSanchez)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblApellidosSanchez)
                        .addGap(10, 10, 10)
                        .addComponent(lblFuerzaPopular1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JPanelKeiko1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(lblFotoSanchez)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblVotosSanchez)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        cboAmbito.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TODOS", "PERÚ", "EXTRANJERO" }));
        cboAmbito.addItemListener(this::cboAmbitoItemStateChanged);
        cboAmbito.addActionListener(this::cboAmbitoActionPerformed);

        cboRegion.addItemListener(this::cboRegionItemStateChanged);
        cboRegion.addActionListener(this::cboRegionActionPerformed);

        lblAmbito.setText("ÁMBITO:");

        lblRegion.setText("----------------");

        jLabel1.setBackground(new java.awt.Color(0, 0, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 102));
        jLabel1.setText("Votos Keiko");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 102));
        jLabel2.setText("Votos Sánchez");

        txtVotosKeiko.addActionListener(this::txtVotosKeikoActionPerformed);

        txtVotosSanchez.addActionListener(this::txtVotosSanchezActionPerformed);

        btnRegistrar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnRegistrar.setForeground(new java.awt.Color(0, 51, 102));
        btnRegistrar.setText("Registrar Votos");
        btnRegistrar.addActionListener(this::btnRegistrarActionPerformed);

        btnReporte_G1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnReporte_G1.setForeground(new java.awt.Color(0, 51, 102));
        btnReporte_G1.setText("Reporte General");
        btnReporte_G1.addActionListener(this::btnReporte_G1ActionPerformed);

        btnReporte_G2.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnReporte_G2.setForeground(new java.awt.Color(0, 51, 102));
        btnReporte_G2.setText("Reporte por Pais y Extrajero");
        btnReporte_G2.addActionListener(this::btnReporte_G2ActionPerformed);

        btnLimpiar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnLimpiar.setForeground(new java.awt.Color(0, 51, 102));
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(this::btnLimpiarActionPerformed);

        btnCerrar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnCerrar.setForeground(new java.awt.Color(0, 51, 102));
        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(this::btnCerrarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtVotosKeiko, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(129, 129, 129)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtVotosSanchez, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnReporte_G1)
                        .addGap(106, 106, 106)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(74, 74, 74)
                        .addComponent(btnReporte_G2, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)))
                .addGap(45, 45, 45))
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblAmbito)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboAmbito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblRegion, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboRegion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(JPanelKeiko, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addComponent(JPanelKeiko1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboRegion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboAmbito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAmbito)
                    .addComponent(lblRegion))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(JPanelKeiko1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JPanelKeiko, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtVotosKeiko, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtVotosSanchez, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnReporte_G1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnReporte_G2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(57, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 41, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboAmbitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboAmbitoActionPerformed
        // TODO add your handling code here:
        actualizarSelectores();
    }//GEN-LAST:event_cboAmbitoActionPerformed

    private void cboRegionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboRegionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboRegionActionPerformed

    private void txtVotosKeikoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVotosKeikoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVotosKeikoActionPerformed

    private void txtVotosSanchezActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVotosSanchezActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVotosSanchezActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:
        // Leer valores de los combos
        String ambito = cboAmbito.getSelectedItem().toString();
        String region = cboRegion.getSelectedItem().toString();

        if (ambito.equals("TODOS") || cboRegion.getSelectedItem() == null) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Seleccione un ámbito y una región válidos",
                    "Selección inválida", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // Determinar tipo según ámbito
        String tipo = ambito.equals("PERÚ") ? "REGIÓN" : "CONTINENTE";
   
        int votosKeiko, votosSanchez;
        try {
            votosKeiko = Integer.parseInt(txtVotosKeiko.getText().trim());
            votosSanchez = Integer.parseInt(txtVotosSanchez.getText().trim());

            if (votosKeiko < 0 || votosSanchez < 0) {
                javax.swing.JOptionPane.showMessageDialog(this,
                        "Los votos no pueden ser negativos",
                        "Valor inválido", javax.swing.JOptionPane.WARNING_MESSAGE);
                return;
            }
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Ingrese números enteros válidos en los campos de votos.",
                    "Formato inválido", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
   
        // --- Registrar y actualizar ---
        service.registrarVotos(tipo, region, votosKeiko, votosSanchez);
        actualizarResultados();
        actualizarListado();
        txtVotosKeiko.setText("");
        txtVotosSanchez.setText("");

        javax.swing.JOptionPane.showMessageDialog(this,
                "Votos registrados correctamente.", "Éxito",
                javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void cboAmbitoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboAmbitoItemStateChanged
        // TODO add your handling code here:
        if (evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
            actualizarResultados();
        }
    }//GEN-LAST:event_cboAmbitoItemStateChanged

    private void cboRegionItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboRegionItemStateChanged
        // TODO add your handling code here:
        if (evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
            actualizarResultados();
        }
    }//GEN-LAST:event_cboRegionItemStateChanged

    private void btnReporte_G1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporte_G1ActionPerformed
        // TODO add your handling code here:
        Reporte_General dlg = new Reporte_General(this, true);
        dlg.cargarDatos(service.obtenerTodos());

        dlg.setLocationRelativeTo(this);
        dlg.setVisible(true);

    }//GEN-LAST:event_btnReporte_G1ActionPerformed

    private void btnReporte_G2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporte_G2ActionPerformed
        // TODO add your handling code here:
        Reporte_Peru_Extranjero dlg = new Reporte_Peru_Extranjero(this, true);

        ResultadosTotales peru = service.obtenerTotalesPorTipo("REGIÓN");

        ResultadosTotales extranjero = service.obtenerTotalesPorTipo("CONTINENTE");

        dlg.cargarTotales(peru, extranjero);

        dlg.setLocationRelativeTo(this);
        dlg.setVisible(true);
    }//GEN-LAST:event_btnReporte_G2ActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        String ambito = cboAmbito.getSelectedItem().toString();
        String region = cboRegion.getSelectedItem() != null
                ? cboRegion.getSelectedItem().toString() : "";

        int confirm = JOptionPane.showConfirmDialog(
                this,
                "¿Seguro que deseas limpiar los datos mostrados?",
                "Confirmar",
                JOptionPane.YES_NO_OPTION
        );

        if (confirm != JOptionPane.YES_OPTION) return;

        if (ambito.equals("TODOS")) {
            service.limpiarDatos();
        } else if (ambito.equals("PERÚ")) {
            if (region.isEmpty() || region.equalsIgnoreCase("--")) {
                service.limpiarPorTipo("REGIÓN");
            } else {
                service.limpiarPorUbicacion(region);
            }
        } else {
            if (region.isEmpty() || region.equalsIgnoreCase("--")) {
                service.limpiarPorTipo("CONTINENTE");
            } else {
                service.limpiarPorUbicacion(region);
            }
        }

        actualizarResultados();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void actualizarSelectores() {
        cboRegion.removeAllItems();
        String ambito = cboAmbito.getSelectedItem().toString();

        if (ambito.equals("PERÚ")) {

            lblRegion.setText("REGIÓN");

            for (String region : data.get("PERÚ")) {
                cboRegion.addItem(region);
            }

        } else if (ambito.equals("EXTRANJERO")) {

            lblRegion.setText("CONTINENTE");

            for (String cont : data.get("EXTRANJERO")) {
                cboRegion.addItem(cont);
            }

        } 
        else if (ambito.equals("TODOS")) {

            lblRegion.setText("--------------------");

            cboRegion.addItem("—");
        }
    }
    
    private void actualizarResultados() {
        capa_logica.VotacionServicio.ResultadosTotales totales;
        String ambito = cboAmbito.getSelectedItem().toString();
        String region = cboRegion.getSelectedItem() != null
                ? cboRegion.getSelectedItem().toString() : "";
        if (ambito.equals("TODOS")) {
            totales = service.obtenerTotales();

        } else if (ambito.equals("PERÚ")) {
            if (region.isEmpty() || region.equalsIgnoreCase("--")) {
                totales = service.obtenerTotalesPorTipo("REGIÓN");
            } else {
                totales = service.obtenerTotalesPorUbicacion(region);
            }
        } else {
            if (region.isEmpty() || region.equalsIgnoreCase("--")) {
                totales = service.obtenerTotalesPorTipo("CONTINENTE");
            } else {
                totales = service.obtenerTotalesPorUbicacion(region);
            }
        }
        
        lblVotosKeiko.setText(String.valueOf(totales.getTotalKeiko()+" votos"));
        lblVotosSanchez.setText(String.valueOf(totales.getTotalSanchez()+" votos"));
        lblPorcentajeKeiko.setText(String.format("%.2f%%", totales.getPorcentajeKeiko()));
        lblPorcentajeSanchez.setText(String.format("%.2f%%", totales.getPorcentajeSanchez()));
    }
    
    private void actualizarListado() {
        List<Voto> lista = service.obtenerTodos();

        String texto = "";

        texto += "TIPO\tUBICACION\tKEIKO\tSANCHEZ\t%K\t%S\n";
        texto += "-----------------------------------------------------------\n";

        for (Voto v : lista) {

            int total = v.getVotosKeiko() + v.getVotosSanchez();

            double porcKeiko =
                total == 0 ? 0 :
                (v.getVotosKeiko() * 100.0) / total;

            double porcSanchez =
                total == 0 ? 0 :
                (v.getVotosSanchez() * 100.0) / total;

            texto += v.getTipo() + "\t"
                    + v.getUbicacion() + "\t"
                    + v.getVotosKeiko() + "\t"
                    + v.getVotosSanchez() + "\t"
                    + String.format("%.2f%%", porcKeiko) + "\t"
                    + String.format("%.2f%%", porcSanchez)
                    + "\n";
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPanelKeiko;
    private javax.swing.JPanel JPanelKeiko1;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnReporte_G1;
    private javax.swing.JButton btnReporte_G2;
    private javax.swing.JComboBox<String> cboAmbito;
    private javax.swing.JComboBox<String> cboRegion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAmbito;
    private javax.swing.JLabel lblApellidosKeiko1;
    private javax.swing.JLabel lblApellidosSanchez;
    private javax.swing.JLabel lblFotoKeiko;
    private javax.swing.JLabel lblFotoSanchez;
    private javax.swing.JLabel lblFuerzaPopular;
    private javax.swing.JLabel lblFuerzaPopular1;
    private javax.swing.JLabel lblNombresKeiko;
    private javax.swing.JLabel lblNombresSanchez;
    private javax.swing.JLabel lblPorcentajeKeiko;
    private javax.swing.JLabel lblPorcentajeSanchez;
    private javax.swing.JLabel lblRegion;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblVotosKeiko;
    private javax.swing.JLabel lblVotosSanchez;
    private javax.swing.JTextField txtVotosKeiko;
    private javax.swing.JTextField txtVotosSanchez;
    // End of variables declaration//GEN-END:variables
}
