/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package capa_presentacion;

/**
 *
 * @author NAYR VASQUEZ
 */
public class frmVotacion extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frmVotacion.class.getName());

    /**
     * Creates new form frmVotacion
     */
    public frmVotacion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        JPanelKeiko = new javax.swing.JPanel();
        lblFotoKeiko = new javax.swing.JLabel();
        lblPorcentajeKeiko = new javax.swing.JLabel();
        lblNombresKeiko = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblFuerzaPopular = new javax.swing.JLabel();
        lblApellidosKeiko1 = new javax.swing.JLabel();
        JPanelKeiko1 = new javax.swing.JPanel();
        lblFotoSanchez = new javax.swing.JLabel();
        lblPorcentajeSanchez = new javax.swing.JLabel();
        lblNombresSanchez = new javax.swing.JLabel();
        lblApellidosSanchez = new javax.swing.JLabel();
        lblFuerzaPopular1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(0, 51, 102));
        lblTitulo.setText("Elección de Fórmula Presidencial");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        JPanelKeiko.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblPorcentajeKeiko.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblPorcentajeKeiko.setForeground(new java.awt.Color(0, 51, 102));
        lblPorcentajeKeiko.setText("0.00%");

        lblNombresKeiko.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblNombresKeiko.setForeground(new java.awt.Color(0, 51, 102));
        lblNombresKeiko.setText("KEIKO SOFIA");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 102));
        jLabel1.setText("0 votos");

        lblFuerzaPopular.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblFuerzaPopular.setForeground(new java.awt.Color(153, 153, 153));
        lblFuerzaPopular.setText("FUERZA POPULAR");

        lblApellidosKeiko1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblApellidosKeiko1.setForeground(new java.awt.Color(0, 51, 102));
        lblApellidosKeiko1.setText("FUJIMORI HIGUCHI");

        javax.swing.GroupLayout JPanelKeikoLayout = new javax.swing.GroupLayout(JPanelKeiko);
        JPanelKeiko.setLayout(JPanelKeikoLayout);
        JPanelKeikoLayout.setHorizontalGroup(
            JPanelKeikoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelKeikoLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lblFotoKeiko)
                .addGap(18, 18, 18)
                .addGroup(JPanelKeikoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNombresKeiko)
                    .addComponent(lblPorcentajeKeiko)
                    .addComponent(jLabel1)
                    .addComponent(lblFuerzaPopular)
                    .addComponent(lblApellidosKeiko1))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        JPanelKeikoLayout.setVerticalGroup(
            JPanelKeikoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelKeikoLayout.createSequentialGroup()
                .addGroup(JPanelKeikoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPanelKeikoLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(lblFotoKeiko))
                    .addGroup(JPanelKeikoLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(lblPorcentajeKeiko)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblNombresKeiko)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblApellidosKeiko1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblFuerzaPopular, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        JPanelKeiko1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblPorcentajeSanchez.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblPorcentajeSanchez.setForeground(new java.awt.Color(0, 51, 102));
        lblPorcentajeSanchez.setText("0.00%");

        lblNombresSanchez.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblNombresSanchez.setForeground(new java.awt.Color(0, 51, 102));
        lblNombresSanchez.setText("ROBERTO HELBERT");

        lblApellidosSanchez.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblApellidosSanchez.setForeground(new java.awt.Color(0, 51, 102));
        lblApellidosSanchez.setText("SANCHEZ PALOMINO");

        lblFuerzaPopular1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblFuerzaPopular1.setForeground(new java.awt.Color(153, 153, 153));
        lblFuerzaPopular1.setText("JUNTOS POR EL PERÚ");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 102));
        jLabel2.setText("0 votos");

        javax.swing.GroupLayout JPanelKeiko1Layout = new javax.swing.GroupLayout(JPanelKeiko1);
        JPanelKeiko1.setLayout(JPanelKeiko1Layout);
        JPanelKeiko1Layout.setHorizontalGroup(
            JPanelKeiko1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelKeiko1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblFotoSanchez)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JPanelKeiko1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(lblPorcentajeSanchez)
                    .addComponent(lblNombresSanchez)
                    .addComponent(lblApellidosSanchez)
                    .addComponent(lblFuerzaPopular1))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        JPanelKeiko1Layout.setVerticalGroup(
            JPanelKeiko1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelKeiko1Layout.createSequentialGroup()
                .addGroup(JPanelKeiko1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(JPanelKeiko1Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(lblFotoSanchez))
                    .addGroup(JPanelKeiko1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lblPorcentajeSanchez)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblNombresSanchez)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblApellidosSanchez)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblFuerzaPopular1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(JPanelKeiko, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JPanelKeiko1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(70, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(JPanelKeiko1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JPanelKeiko, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(126, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new frmVotacion().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPanelKeiko;
    private javax.swing.JPanel JPanelKeiko1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblApellidosKeiko1;
    private javax.swing.JLabel lblApellidosSanchez;
    private javax.swing.JLabel lblFotoKeiko;
    private javax.swing.JLabel lblFotoSanchez;
    private javax.swing.JLabel lblFuerzaPopular;
    private javax.swing.JLabel lblFuerzaPopular1;
    private javax.swing.JLabel lblNombresKeiko;
    private javax.swing.JLabel lblNombresSanchez;
    private javax.swing.JLabel lblPorcentajeKeiko;
    private javax.swing.JLabel lblPorcentajeSanchez;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
